openapi: 3.0.1
servers:
  - url: http://192.168.1.1
info:
  description: Test out THETA Camera API Commands here!
  version: 1.0.0
  title: THETA Camera API Testing
  contact:
    name: Github - Project Started by AirTechWick
    url: https://github.com/AirTechWick/testing-swagger

paths:
  /osc/info:
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - Protocols
  /osc/state:
    summary: >-
      Acquires the camera states.  Use CheckForUpdates to check whether the
      state object has changed its contents.
    description: >-
      Acquires the camera states.  Use CheckForUpdates to check whether the
      state object has changed its contents.
    post:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - Protocols
  /osc/commands/execute:
    summary: >-
      Starts still image shooting.  If exposureDelay is enabled, self-timer
      shooting is started.
    description: >-
      Starts still image shooting.  If exposureDelay is enabled, self-timer
      shooting is started.
    post:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - Commands
